AWSTemplateFormatVersion: "2010-09-09"
Description: "ecs for task"

Parameters:
  VpcId:
    Type: String
  SubnetIds:
    Type: CommaDelimitedList
  ImgVer:
    Type: String
    Default: latest
  ProjectName:
    Type: String
    Default: "sample-ecs-executor"
  Region:
    Type: String
    Default: "ap-northeast-1"

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/${ProjectName}"
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-ecs-task-execution-role
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-execution-role"
        - Key: Group
          Value: !Sub "${ProjectName}"
  BatchServiceEventTargetRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-service-event-target-role
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/AWSBatchServiceEventTargetRole"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-service-event-target-role
        - Key: Group
          Value: !Sub ${ProjectName}
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      NetworkMode: awsvpc
      Cpu: 4096
      Memory: 8192
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      Family: !Sub "${ProjectName}"
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Image: !Sub '{{resolve:ssm:${ProjectName}-ecr-repository-uri}}:${ImgVer}'
          Name: !Sub "${ProjectName}-task"
          Cpu: 4096
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub "/ecs/${ProjectName}"
              awslogs-region: !Sub "${Region}"
              awslogs-stream-prefix: ecs
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-task-definition"
        - Key: Group
          Value: !Sub "${ProjectName}"
  # -----------------------------------------------------------
  #                          Job Events
  # -----------------------------------------------------------
  EventsAll:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${ProjectName}-job
      ScheduleExpression: cron(00 16 * * ? *)
      State: ENABLED
      Targets:
        - Id: !Sub ${ProjectName}-job
          Arn: !Ref JobQueue
          RoleArn: !GetAtt BatchServiceEventTargetRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref TaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                AssignPublicIp:  ENABLED
                Subnets:
                  Ref: SubnetIds
